#include "rasp.h"

/* Per-build enforcement config, generated by pack_app.py into rasp_config.h.
 * Falls back to safe defaults so the module also compiles in the standalone
 * fixture native build (build.py), which does not run the packer. */
#if defined(__has_include)
#  if __has_include("rasp_config.h")
#    include "rasp_config.h"
#  endif
#endif

/* action values: 0 = off, 1 = report, 2 = enforce */
#ifndef RASP_ACT_FRIDA
#define RASP_ACT_FRIDA 2
#endif
#ifndef RASP_ACT_DEBUG
#define RASP_ACT_DEBUG 2
#endif
#ifndef RASP_ACT_ROOT
#define RASP_ACT_ROOT 1
#endif
#ifndef RASP_ACT_EMULATOR
#define RASP_ACT_EMULATOR 1
#endif
#ifndef RASP_CRYPTO_GATE
#define RASP_CRYPTO_GATE 1
#endif

#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <dirent.h>
#include <errno.h>
#include <poll.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* ---- small io helpers (no heap) ---- */

static int file_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0;
}

/* Read up to cap-1 bytes of a file into buf (NUL-terminated). Returns bytes read, or -1. */
static long read_file(const char *path, char *buf, long cap) {
    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return -1;
    long total = 0;
    for (;;) {
        long room = cap - 1 - total;
        if (room <= 0) break;
        ssize_t n = read(fd, buf + total, (size_t) room);
        if (n < 0) { if (total == 0) { close(fd); return -1; } break; }
        if (n == 0) break;
        total += n;
    }
    close(fd);
    buf[total] = '\0';
    return total;
}

static int contains(const char *hay, long haylen, const char *needle) {
    long nlen = (long) strlen(needle);
    if (nlen == 0 || haylen < nlen) return 0;
    for (long i = 0; i + nlen <= haylen; i++) {
        if (hay[i] == needle[0] && memcmp(hay + i, needle, (size_t) nlen) == 0) return 1;
    }
    return 0;
}

/* Scan a large pseudo-file (e.g. /proc/self/maps) in overlapping chunks for any needle. */
static int scan_proc_for(const char *path, const char *const *needles, int nn) {
    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    enum { CHUNK = 8192, KEEP = 64 };
    char buf[CHUNK + KEEP + 1];
    long carry = 0;
    int hit = 0;
    for (;;) {
        ssize_t n = read(fd, buf + carry, CHUNK);
        if (n <= 0) break;
        long len = carry + n;
        buf[len] = '\0';
        for (int i = 0; i < nn; i++) {
            if (contains(buf, len, needles[i])) { hit = 1; break; }
        }
        if (hit) break;
        /* keep the tail so a needle split across chunk boundary is still found */
        if (len > KEEP) { memmove(buf, buf + len - KEEP, KEEP); carry = KEEP; }
        else carry = len;
    }
    close(fd);
    return hit;
}

/* ---- Frida / dynamic instrumentation ---- */

/* Scan this process's thread names for Frida's runtime threads. These survive even when
 * the agent's memfd name is hidden, so they are the most reliable modern-Frida signal.
 * Only Frida/Gum-specific names are used to avoid false positives on the enforced path. */
static int threads_have_frida(void) {
    DIR *d = opendir("/proc/self/task");
    if (!d) return 0;
    static const char *tnames[] = { "gum-js-loop", "pool-frida", "frida-gadget" };
    struct dirent *e;
    int hit = 0;
    char path[80], name[64];
    while ((e = readdir(d)) != NULL) {
        if (e->d_name[0] < '0' || e->d_name[0] > '9') continue;   /* tid dirs only */
        snprintf(path, sizeof path, "/proc/self/task/%s/comm", e->d_name);
        long n = read_file(path, name, sizeof name);
        if (n <= 0) continue;
        for (int i = 0; i < (int)(sizeof tnames / sizeof tnames[0]); i++) {
            if (contains(name, n, tnames[i])) { hit = 1; break; }
        }
        if (hit) break;
    }
    closedir(d);
    return hit;
}

/*
 * Detect a running frida-server by connecting to its default control port on loopback.
 * Unlike reading /proc/net/tcp (SELinux-denied to untrusted apps), an outbound loopback
 * connect() is permitted. A closed port returns ECONNREFUSED immediately, so this costs
 * nothing when Frida is absent. On connect we send a D-Bus AUTH line: frida-server speaks
 * D-Bus and replies (typically "REJECTED ..."), which confirms it is Frida rather than an
 * unrelated service squatting the port.
 */
static int probe_frida_port(int port) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return 0;
    /* non-blocking connect with a short timeout */
    int fl = fcntl(fd, F_GETFL, 0);
    fcntl(fd, F_SETFL, fl | O_NONBLOCK);

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof addr);
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t) port);
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);   /* 127.0.0.1 */

    int rc = connect(fd, (struct sockaddr *) &addr, sizeof addr);
    if (rc != 0 && errno != EINPROGRESS) { close(fd); return 0; }
    if (rc != 0) {
        struct pollfd pw = { fd, POLLOUT, 0 };
        if (poll(&pw, 1, 300) <= 0) { close(fd); return 0; }
        int soerr = 0; socklen_t l = sizeof soerr;
        getsockopt(fd, SOL_SOCKET, SO_ERROR, &soerr, &l);
        if (soerr != 0) { close(fd); return 0; }       /* refused / unreachable */
    }
    /* A port number alone is not proof: another local service may use it. Only a
     * recognizable D-Bus authentication reply is an enforceable Frida signal. */
    int detected = 0;
    const char auth[] = { 0x00, 'A','U','T','H','\r','\n' };
    (void) send(fd, auth, sizeof auth, MSG_NOSIGNAL);
    struct pollfd pr = { fd, POLLIN, 0 };
    if (poll(&pr, 1, 300) > 0) {
        char buf[64];
        ssize_t n = recv(fd, buf, sizeof buf - 1, 0);
        if (n > 0) {
            /* An unauthenticated D-Bus peer rejects the bare AUTH request with
             * a REJECTED mechanism list. Generic replies are not enforceable. */
            if (contains(buf, n, "REJECTED")) detected = 1;
        }
    }
    close(fd);
    return detected;
}

/* True if a frida-server is listening on either default port on this device. */
static int frida_server_present(void) {
    if (probe_frida_port(27042)) return 1;
    if (probe_frida_port(27043)) return 1;
    return 0;
}

int rasp_frida_present(void) {
    /* Frida-specific tokens only — avoid generic names (e.g. "gmain") that legitimate
     * libraries may contain, since a false positive on the enforced path blocks launch. */
    static const char *needles[] = {
        "frida", "frida-agent", "frida-gadget", "gum-js-loop",
        "linjector", "libgadget", "re.frida.server"
    };
    /* Primary signal: an injected agent/gadget shows up in the process memory map
     * (e.g. "/memfd:frida-agent-64.so"). */
    if (scan_proc_for("/proc/self/maps", needles, (int)(sizeof needles / sizeof needles[0]))) return 1;
    /* Defense-in-depth: Frida/Gum runtime thread names, which the agent cannot easily hide. */
    if (threads_have_frida()) return 1;
    /* A frida-server running on the device, even before it injects into this app. */
    if (frida_server_present()) return 1;
    /* frida-server dropped in the usual staging dir. */
    if (file_exists("/data/local/tmp/re.frida.server")) return 1;
    if (file_exists("/data/local/tmp/frida-server")) return 1;
    return 0;
}

/* ---- Debugger ---- */

int rasp_debugger_present(void) {
    char buf[4096];
    long n = read_file("/proc/self/status", buf, sizeof buf);
    if (n <= 0) return 0;
    const char *p = strstr(buf, "TracerPid:");
    if (!p) return 0;
    p += 10;
    while (*p == ' ' || *p == '\t') p++;
    /* any non-zero tracer pid means a debugger/ptrace supervisor is attached */
    return (*p != '0') ? 1 : 0;
}

/* ---- Root ---- */

/*
 * KernelSU detection via its prctl "backdoor". KSU hooks prctl() and, for the magic
 * option KERNEL_SU_OPTION with CMD_GET_VERSION, writes its version into the arg pointer.
 * An unmodified kernel does not recognize the option and leaves the value untouched, so a
 * non-zero result means KSU is active. This works from an unprivileged app and catches KSU
 * even when it hides its mounts and /data/adb is SELinux-unreadable (which defeats the
 * path/mountinfo checks below). Very low false-positive: 0xDEADBEEF is not a real option.
 */
static int ksu_present(void) {
    int version = 0;
    /* prctl(int, ulong, ulong, ulong, ulong); the magic value is used bit-for-bit. */
    prctl((int) 0xDEADBEEF, 2 /* CMD_GET_VERSION */, (unsigned long) &version, 0, 0);
    return version != 0;
}

int rasp_root_present(void) {
    if (ksu_present()) return 1;   /* KernelSU (stealthier than Magisk) */

    static const char *paths[] = {
        "/system/bin/su", "/system/xbin/su", "/sbin/su", "/su/bin/su",
        "/system/bin/.ext/.su", "/system/xbin/mu", "/system/app/Superuser.apk",
        "/data/adb/magisk", "/data/adb/modules", "/data/adb/ksu", "/sbin/.magisk",
        "/init.magisk.rc", "/system/bin/magisk", "/dev/.magisk"
    };
    for (int i = 0; i < (int)(sizeof paths / sizeof paths[0]); i++) {
        if (file_exists(paths[i])) return 1;
    }
    /* Magisk / overlay traces in the mount table. */
    char buf[65536];
    long n = read_file("/proc/self/mountinfo", buf, sizeof buf);
    if (n > 0 && (contains(buf, n, "magisk") || contains(buf, n, "KSU") || contains(buf, n, "/sbin/.magisk"))) {
        return 1;
    }
    return 0;
}

/* ---- Emulator ---- */

int rasp_emulator_present(void) {
    static const char *paths[] = {
        "/dev/socket/qemud", "/dev/qemu_pipe", "/dev/goldfish_pipe",
        "/system/lib/libc_malloc_debug_qemu.so", "/sys/qemu_trace",
        "/system/bin/qemu-props"
    };
    for (int i = 0; i < (int)(sizeof paths / sizeof paths[0]); i++) {
        if (file_exists(paths[i])) return 1;
    }
    char buf[8192];
    long n = read_file("/proc/cpuinfo", buf, sizeof buf);
    if (n > 0 && (contains(buf, n, "goldfish") || contains(buf, n, "ranchu"))) return 1;
    return 0;
}

/* ---- aggregate + op-bound gate ---- */

uint32_t rasp_scan(void) {
    uint32_t f = 0;
    if (rasp_frida_present())    f |= RASP_FRIDA;
    if (rasp_debugger_present()) f |= RASP_DEBUGGER;
    if (rasp_root_present())     f |= RASP_ROOT;
    if (rasp_emulator_present()) f |= RASP_EMULATOR;
    return f;
}

int rasp_block_key(void) {
#if RASP_CRYPTO_GATE
    if (RASP_ACT_FRIDA == 2 && rasp_frida_present())    return 1;
    if (RASP_ACT_DEBUG == 2 && rasp_debugger_present()) return 1;
#endif
    return 0;
}
